Repository teloxide/teloxide, pull requests merged in 2024-04, with the labels that each got.

#1037 Changed `escape` functions in both html and markdown utils to do less allocations and also be slightly faster
  crates/teloxide/src/utils/html.rs
  crates/teloxide/src/utils/markdown.rs
Labels: S-waiting-on-review, C-main

#1046 fix: typo in errors.rs ToMuchMessages
  CHANGELOG.md
  crates/teloxide-core/src/errors.rs
Labels: S-waiting-on-review, C-core, A-tba-errors

#1049 Update README.md
  README.md
Labels: S-waiting-on-review
