Repository teloxide/teloxide, pull requests merged in 2024-03, with the labels that each got.

#1023 Fix CI & make sure dependency auto updates can't fail CI
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  Cargo.lock
Labels: S-waiting-on-review, A-meta

#1027 Update dependabot.yml
  .github/dependabot.yml
Labels: S-waiting-on-review

#1005 Implement `GetChatId` for `teloxide-core::types::*`
  CHANGELOG.md
  crates/teloxide/src/dispatching/dialogue/get_chat_id.rs
Labels: S-waiting-on-review, C-main, A-dialogue, A-dispatching
