Repository teloxide/teloxide, pull requests merged in 2025-03, with the labels that each got.

#1291 Bump deadpool-redis to 0.20
  CHANGELOG.md
  Cargo.lock
  crates/teloxide/Cargo.toml
Labels: S-waiting-on-review, C-main

#1287 Update `ApiError::MessageToReplyNotFound` text
  crates/teloxide-core/src/errors.rs
Labels: S-waiting-on-review, C-core, A-tba-errors

#1285 Also parse commands from captions
  CHANGELOG.md
  crates/teloxide/src/dispatching/handler_ext.rs
Labels: S-waiting-on-review, C-main, A-dispatching

#1300 Describe how to pull from Git
  README.md
Labels: S-waiting-on-review

#1302 Update the changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#1303 Add `.mailmap`
  .mailmap
Labels: S-waiting-on-review

#1305 Link the WebApp example in the README
  README.md
Labels: S-waiting-on-review

#1306 Make `provider_token` field optional
  MIGRATION_GUIDE.md
  crates/teloxide-core/CHANGELOG.md
  crates/teloxide-core/schema.ron
  crates/teloxide-core/src/adaptors/erased.rs
  crates/teloxide-core/src/bot/api.rs
  crates/teloxide-core/src/local_macros.rs
  crates/teloxide-core/src/payloads/create_invoice_link.rs
  crates/teloxide-core/src/payloads/send_invoice.rs
  crates/teloxide-core/src/requests/requester.rs
  crates/teloxide-core/src/types/input_message_content.rs
Labels: S-waiting-on-review, C-core, A-tba-types, A-requester, A-requests

#1308 Update `triagebot.toml`
  triagebot.toml
Labels: S-waiting-on-review

#1307 Bump license year
  LICENSE
Labels: S-waiting-on-review

#1309 Release v0.14.0
  CHANGELOG.md
  Cargo.lock
  MIGRATION_GUIDE.md
  README.md
  crates/teloxide-core/CHANGELOG.md
  crates/teloxide-core/Cargo.toml
  crates/teloxide-core/README.md
  crates/teloxide-core/src/lib.rs
  crates/teloxide-macros/CHANGELOG.md
  crates/teloxide-macros/Cargo.toml
  crates/teloxide/Cargo.toml
Labels: S-waiting-on-review, C-core, C-macros, C-main, A-macros

#1311 Bump nightly to 2025-03-30 and fix arising errors
  .devcontainer/Containerfile
  .github/workflows/ci.yml
  CHANGELOG.md
  Cargo.lock
  crates/teloxide-core/CHANGELOG.md
  crates/teloxide-core/src/codegen.rs
  crates/teloxide-core/src/lib.rs
  crates/teloxide-core/src/local_macros.rs
  crates/teloxide-core/src/types/maybe_inaccessible_message.rs
  crates/teloxide/Cargo.toml
  crates/teloxide/src/dispatching/dispatcher.rs
  crates/teloxide/src/features.md
  rust-toolchain.toml
Labels: S-waiting-on-review, C-core, C-main, A-tba-types, A-dispatching

#1312 Release v0.14.1
  CHANGELOG.md
  Cargo.lock
  README.md
  crates/teloxide-core/CHANGELOG.md
  crates/teloxide-core/Cargo.toml
  crates/teloxide-core/README.md
  crates/teloxide-core/src/lib.rs
  crates/teloxide/Cargo.toml
Labels: S-waiting-on-review, C-core, C-main

#1314 Implement `Clone` for `RequestError` & `DownloadError`
  CHANGELOG.md
  crates/teloxide-core/src/errors.rs
  crates/teloxide-core/src/net/download.rs
  crates/teloxide-core/src/net/request.rs
  crates/teloxide-core/src/serde_multipart/error.rs
Labels: S-waiting-on-review, C-core, A-tba-errors

#1310 Add the middlewares example
  Cargo.lock
  crates/teloxide/Cargo.toml
  crates/teloxide/examples/middlewares.rs
Labels: WIP, S-waiting-on-review, C-main

#1317 Fix a typo
  crates/teloxide/examples/middlewares.rs
Labels: S-waiting-on-review, C-main
